name: Publish docker image
on: release

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    container: sbtscala/scala-sbt:eclipse-temurin-alpine-24.0.1_9_1.11.1_3.7.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run sbt Docker/publish
        run: VERSION=${{github.event.release.tag_name}} sbt Docker/publish
